[build]
publish = "dist/apps/portfolio-next/"
command   = "npm run build:portfolio-next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[context.production]
  environment = { NETLIFY_NEXT_PLUGIN_SKIP = "true" }
