name: CI

on: pull_request
#on: [pull_request, push]

jobs:
  typos:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@v1
      - uses: crate-ci/typos@v1.26.0
        with:
          files: .
  show:
    runs-on: ubuntu-latest
    steps:
      - name: Show Env
        # run: echo "Env ${{ env.ENV_ID }}
        run: echo "Env for ci website pr"
