name: CI

on: pull_request
#on: [pull_request, push]

jobs:
  spelling:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
#        uses: actions/checkout@v4
        uses: actions/checkout@main
      - name: Spell Check Repo
        uses: crate-ci/typos@master
#  typos:
#    name: Spell Check
#    runs-on: ubuntu-latest
#    steps:
#      - uses: taiki-e/checkout-action@v1
#      - uses: crate-ci/typos@v1.26.0
#        with:
#          files: .
