name: CI

on: pull_request
#on: [pull_request, push]

jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - name: Show Env
       # run: echo "Env ${{ env.ENV_ID }}
        run: echo "Env for ci website pr"