name: Check PR

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  #  update-pr-description:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout
  #        uses: actions/checkout@v4
  #      - name: Update PR Description
  #        uses: nefrob/pr-description@v1.1.2
  #        with:
  #          content: "Hello there!"
  #          regex: ".*"
  #          regexFlags: s
  #          token: ${{ secrets.GITHUB_TOKEN }}
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Show Env
        # run: echo "Env ${{ env.ENV_ID }}
        run: echo "Env for ci website pr"
